import type { Config } from "tailwindcss";

/**
 * Ported 1:1 from the Stitch "Midnight Cinematic" design system (AETHER).
 * Font families are wired to the next/font CSS variables injected in app/layout.tsx.
 */
const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#d0f100",
        "tertiary-container": "#c3aa5a",
        "on-surface": "#e3e2e6",
        "primary-fixed": "#ffdadb",
        "inverse-primary": "#be003d",
        "on-tertiary-fixed": "#231b00",
        "on-tertiary-fixed-variant": "#564500",
        "on-primary-fixed-variant": "#91002c",
        "on-background": "#e3e2e6",
        "on-secondary": "#2c3400",
        "secondary-fixed": "#d0f100",
        tertiary: "#dfc573",
        secondary: "#ffffff",
        "primary-fixed-dim": "#ffb2b8",
        "on-secondary-fixed": "#181e00",
        "tertiary-fixed": "#fce18b",
        "surface-variant": "#343538",
        "pitch-black": "#000000",
        "on-primary-fixed": "#40000f",
        "on-secondary-fixed-variant": "#404c00",
        "surface-bright": "#38393c",
        "surface-container": "#1e2022",
        outline: "#ab888a",
        "silver-mist": "#9ea0a9",
        "surface-deep": "#272c33",
        "surface-container-lowest": "#0d0e11",
        "on-tertiary": "#3c2f00",
        "pure-white": "#ffffff",
        "on-error-container": "#ffdad6",
        "secondary-fixed-dim": "#b6d300",
        error: "#ffb4ab",
        "on-primary-container": "#ffffff",
        "surface-container-low": "#1a1b1e",
        background: "#121316",
        "outline-variant": "#5b3f41",
        "surface-dim": "#121316",
        "on-tertiary-container": "#4e3e00",
        primary: "#ffb2b8",
        "surface-container-high": "#292a2d",
        "tertiary-fixed-dim": "#dfc572",
        "on-error": "#690005",
        "inverse-on-surface": "#2f3033",
        surface: "#121316",
        "primary-container": "#e32652",
        "inverse-surface": "#e3e2e6",
        "error-container": "#93000a",
        "on-surface-variant": "#e4bdbf",
        "surface-tint": "#ffb2b8",
        "on-primary": "#67001d",
        "on-secondary-container": "#5c6b00",
        "surface-container-highest": "#343538",
        "charcoal-canvas": "#222326",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "container-max": "1440px",
        "margin-mobile": "20px",
        "margin-desktop": "48px",
        "section-gap": "64px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      fontFamily: {
        "display-xl": ["var(--font-anton)", "sans-serif"],
        "display-lg": ["var(--font-anton)", "sans-serif"],
        "display-lg-mobile": ["var(--font-anton)", "sans-serif"],
        "headline-md": ["var(--font-inter)", "sans-serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "label-caps": ["var(--font-inter)", "sans-serif"],
        "accent-serif": ["var(--font-playfair)", "serif"],
      },
      fontSize: {
        "display-lg-mobile": ["48px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "display-lg": ["64px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "accent-serif": ["64px", { lineHeight: "72px", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-xl": ["80px", { lineHeight: "80px", letterSpacing: "-0.04em", fontWeight: "400" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};

export default config;
